# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'wbuRewrite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for wbuRewrite
  pod 'Bolts'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'Firebase/Messaging'

  #target 'wbuRewrite-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

  target 'wbuRewriteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

#target 'wbuRewrite-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for wbuRewrite-tvOS

  #target 'wbuRewrite-tvOSTests' do
    #inherit! :search_paths
    # Pods for testing
  #end

#end
